### ISSUE TITLE
OG Data - question

### ISSUE THREAD

**Issue by davidflores2** [Gainesville-Barcamp/Gainesville-Barcamp#22]
I see an `og:image` tag on the header, question, do we need the rest like `description`,`title`, `url` [etc](https://developers.facebook.com/docs/sharing/best-practices#tags)?

**Comment by mherchel** [comment]
Facebook will automatically pull down the description from the `meta description`, and the title from the title tag. Honestly, I never knew what the benefits of those tags were :)

**Comment by davidflores2** [comment]
Yeah, right. 
It is good when you want to use something different from what the meta description says. Like if you want to customize the FB message but you're right. FB will get it from the meta if the og is not there.
