### ISSUE TITLE
Prospectus needs info on how to be a sponsor

### ISSUE THREAD

**Issue by mherchel** [Gainesville-Barcamp/Gainesville-Barcamp#26]
The PDF exists, but how do they give us money? Can we do online? Check?

**Comment by davidflores2** [comment]
Is the PDF ready with the new info? If not, I can have this by today?Also, a check is fine.

**Comment by mherchel** [comment]
Yep. Files are in #16

**Comment by mherchel** [comment]
and the final file (with the text outlined) is on the site at http://gainesvillebarcamp.com/prospectus.html

**Comment by davidflores2** [comment]
Got it!
