### ISSUE TITLE
Spelling error in PDF

### ISSUE THREAD

**Issue by kredon** [Gainesville-Barcamp/Gainesville-Barcamp#27]
Take the "e" out of country.

"Be a part of BarCamp Gainesville and join a
much larger movement across the countery.
Get exposure to great ideas, people, and a
super unique experience."
http://gainesvillebarcamp.com/barcamp_prospectus.pdf

**Comment by kredon** [comment]
Also add web address.

**Comment by mherchel** [comment]
@kredon you get this fixed yet? Upload it to the website?

**Comment by kredon** [comment]
I'll push it up tonight.

**Comment by kredon** [comment]
Fixed and committed.
